name: wled
description: A cross-platform application for interacting with WLED devices

version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.3.0
  bitsdojo_window: ^0.1.1+1
  bloc: ^7.2.0
  bloc_concurrency: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_feather_icons: ^2.0.0+1
  flutter_localizations:
    sdk: flutter
  formz: ^0.4.0
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  injectable: ^1.5.0
  json_annotation: ^4.1.0
  multicast_dns: ^0.3.1
  rive: ^0.7.28
  rxdart: ^0.27.2
  url_launcher: ^6.0.12
  webview_flutter: ^2.0.14
  xml: ^5.1.0

dev_dependencies:
  auto_route_generator: ^2.3.0
  build_runner: ^2.1.2
  flutter_app_name: ^0.1.0
  flutter_launcher_icons: 
    git: https://github.com/dirkbo/flutter_launcher_icons.git
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter
  freezed: 
    git:
      url: https://github.com/casvanluijtelaar/freezed.git
      path: packages/freezed
  hive_generator: ^1.1.1
  injectable_generator: ^1.5.1
  json_serializable: ^5.0.2
  mocktail: ^0.2.0
  very_good_analysis: ^2.3.0

dependency_overrides:
  meta: ^1.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/rive/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-Regular.ttf
          weight: 400

# internationalization settings
flutter_intl:
  enabled: true
  class_name: Localization
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n/generated

# set flutter splash screen
flutter_native_splash:
  color: "#1D1D1D"
  image: assets/images/splash.png
  fullscreen: true
  android12: false

# set flutter app icon
flutter_icons:
  ios: true
  android: true
  windows: true
  macos: true
  image_path: "assets/images/fallback.png"
  image_path_ios: "assets/images/fallback.png"
  image_path_android: "assets/images/fallback.png"
  adaptive_icon_background: "assets/images/background.png"
  adaptive_icon_foreground: "assets/images/foreground.png"

# set flutter app name
flutter_app_name:
  name: "WLED"

