name: build
on: [pull_request]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' 

    - name: get packages
      run: flutter pub get

    - name: run code generation
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: run analyzer
      run: flutter analyze
    
    - name: Run tests
      run: flutter test 